# Generated by Django 6.0.7 on 2026-07-29 09:43

import django.db.models.deletion
from django.db import migrations, models


def add_timestamp_fields(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == 'postgresql':
        schema_editor.execute('ALTER TABLE guild_members ADD COLUMN created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;')
        schema_editor.execute('ALTER TABLE guild_members ADD COLUMN updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;')
    else:
        schema_editor.execute('ALTER TABLE guild_members ADD COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;')
        schema_editor.execute('ALTER TABLE guild_members ADD COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;')


def remove_timestamp_fields(apps, schema_editor):
    schema_editor.execute('ALTER TABLE guild_members DROP COLUMN created_at;')
    schema_editor.execute('ALTER TABLE guild_members DROP COLUMN updated_at;')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='GuildMember',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('guild', models.ForeignKey(db_column='guild_id', on_delete=django.db.models.deletion.CASCADE, to='api.guild')),
                        ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                    ],
                    options={
                        'db_table': 'guild_members',
                    },
                ),
                migrations.AlterField(
                    model_name='guild',
                    name='members',
                    field=models.ManyToManyField(related_name='guilds', through='api.GuildMember', to='api.user'),
                ),
                migrations.AddConstraint(
                    model_name='guildmember',
                    constraint=models.UniqueConstraint(fields=('guild', 'user'), name='unique_guild_member'),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_timestamp_fields, remove_timestamp_fields),
            ]
        ),
    ]
