# Generated by Django 6.0.7 on 2026-07-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='author_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
