# Generated by Django 6.0.7 on 2026-07-31 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
