# Generated by Django 6.0.7 on 2026-07-29 11:36

from django.db import migrations, models


def rename_unique_constraint(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == 'postgresql':
        # Drop the auto-generated unique constraint from 0001
        schema_editor.execute('ALTER TABLE guild_members DROP CONSTRAINT IF EXISTS guild_members_guild_id_user_id_5f74972c_uniq;')
        # Drop unique_guild_member if it exists
        schema_editor.execute('ALTER TABLE guild_members DROP CONSTRAINT IF EXISTS unique_guild_member;')
        # Drop target constraint if it exists to avoid collision
        schema_editor.execute('ALTER TABLE guild_members DROP CONSTRAINT IF EXISTS uk_guild_members_guild_id_user_id;')
        # Add the new named unique constraint
        schema_editor.execute('ALTER TABLE guild_members ADD CONSTRAINT uk_guild_members_guild_id_user_id UNIQUE (guild_id, user_id);')
    else:
        try:
            schema_editor.execute('CREATE UNIQUE INDEX IF NOT EXISTS uk_guild_members_guild_id_user_id ON guild_members (guild_id, user_id);')
        except Exception:
            pass


def rollback_unique_constraint(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == 'postgresql':
        schema_editor.execute('ALTER TABLE guild_members DROP CONSTRAINT IF EXISTS uk_guild_members_guild_id_user_id;')
        schema_editor.execute('ALTER TABLE guild_members ADD CONSTRAINT guild_members_guild_id_user_id_5f74972c_uniq UNIQUE (guild_id, user_id);')
    else:
        try:
            schema_editor.execute('DROP INDEX IF EXISTS uk_guild_members_guild_id_user_id;')
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_guildmember_alter_guild_members_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='guildmember',
                    name='unique_guild_member',
                ),
                migrations.AddConstraint(
                    model_name='guildmember',
                    constraint=models.UniqueConstraint(fields=('guild', 'user'), name='uk_guild_members_guild_id_user_id'),
                ),
            ],
            database_operations=[
                migrations.RunPython(rename_unique_constraint, rollback_unique_constraint),
            ]
        ),
    ]
