# Generated by Django 6.0.7 on 2026-09-10 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('permissions', models.BigIntegerField(default=0)),
                ('position', models.IntegerField(default=0)),
                ('is_everyone', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guild', models.ForeignKey(db_column='guild_id', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.guild')),
            ],
            options={
                'db_table': 'roles',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='GuildMemberRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guild_member', models.ForeignKey(db_column='guild_member_id', on_delete=django.db.models.deletion.CASCADE, related_name='member_roles', to='api.guildmember')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, related_name='member_roles', to='api.role')),
            ],
            options={
                'db_table': 'guild_member_roles',
            },
        ),
        migrations.CreateModel(
            name='ChannelPermissionOverwrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('target_type', models.CharField(choices=[('ROLE', 'Role'), ('MEMBER', 'Member')], max_length=16)),
                ('target_id', models.BigIntegerField()),
                ('allow', models.BigIntegerField(default=0)),
                ('deny', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(db_column='channel_id', on_delete=django.db.models.deletion.CASCADE, related_name='overwrites', to='api.channel')),
            ],
            options={
                'db_table': 'channel_permission_overwrites',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('channel', 'target_type', 'target_id'), name='uk_channel_overwrites_channel_target')],
            },
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_everyone', True)), fields=('guild',), name='uk_roles_guild_is_everyone'),
        ),
        migrations.AddConstraint(
            model_name='guildmemberrole',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('guild_member', 'role'), name='uk_guild_member_roles_member_role'),
        ),
    ]
