# Generated by Django 6.0.7 on 2026-07-31

from django.db import migrations


def rename_old_constraints_and_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    constraints = [
        ('channels', 'channels_guild_id_3fc830f2_fk_guilds_id', 'fk_channels_guilds_guild_id'),
        ('guild_members', 'guild_members_guild_id_40cbdaba_fk_guilds_id', 'fk_guild_members_guilds_guild_id'),
        ('guild_members', 'guild_members_user_id_02c3c937_fk_users_id', 'fk_guild_members_users_user_id'),
        ('guilds', 'guilds_owner_id_d39590c9_fk_users_id', 'fk_guilds_users_owner_id'),
        ('messages', 'messages_author_id_6c9e7afb_fk_users_id', 'fk_messages_users_author_id'),
        ('messages', 'messages_channel_id_e10ba908_fk_channels_id', 'fk_messages_channels_channel_id'),
    ]

    indexes = [
        ('channels_guild_id_3fc830f2', 'idx_channels_guild_id'),
        ('guild_members_guild_id_40cbdaba', 'idx_guild_members_guild_id'),
        ('guild_members_user_id_02c3c937', 'idx_guild_members_user_id'),
        ('guilds_owner_id_d39590c9', 'idx_guilds_owner_id'),
        ('messages_author_id_6c9e7afb', 'idx_messages_author_id'),
        ('messages_channel_id_e10ba908', 'idx_messages_channel_id'),
    ]

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT conname FROM pg_constraint;")
        existing_constraints = {r[0] for r in cursor.fetchall()}

        cursor.execute("SELECT indexname FROM pg_indexes;")
        existing_indexes = {r[0] for r in cursor.fetchall()}

        for table, old_name, new_name in constraints:
            if old_name in existing_constraints and new_name not in existing_constraints:
                schema_editor.execute(f'ALTER TABLE {table} RENAME CONSTRAINT {old_name} TO {new_name};')

        for old_name, new_name in indexes:
            if old_name in existing_indexes and new_name not in existing_indexes:
                schema_editor.execute(f'ALTER INDEX {old_name} RENAME TO {new_name};')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_channel_deleted_at_channel_is_deleted_and_more'),
    ]

    operations = [
        migrations.RunPython(rename_old_constraints_and_indexes, migrations.RunPython.noop),
    ]
