set dotenv-load := true

default:
    @just --list

fmt:
    ruff format .
    ruff check --fix .

check:
    ruff format --check .
    ruff check .

test:
    pytest

test-aiven:
    python3 test/test.py

ci:
    just check
    just test
